name: celest_backend
description: The Celest backend for edge_notes_api.
publish_to: none

environment:
  sdk: ^3.4.0

dependencies:
  celest: ^1.0.0
  celest_core: ^1.0.0
  drift: ^2.21.0
  meta: ^1.12.0

dev_dependencies:
  build_runner: ^2.4.13
  drift_dev: ^2.21.0
  lints: ^4.0.0
  test: ^1.25.0
dependency_overrides: {}
